# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: fantamotogp-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fantamotogp
      POSTGRES_PASSWORD: fantamotogp123
      POSTGRES_DB: fantamotogp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fantamotogp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Opzionale: pgAdmin per gestire il DB via web
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fantamotogp-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fantamotogp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: