name: FantaMotoGP Cron Jobs

on:
  schedule:
    # Esegue ogni ora durante i weekend di gara (Venerdì-Lunedì: 0,1,5,6)
    # - cron: '0 * * * 0,1,5,6'
    # Sincronizza i piloti ogni Lunedì alle 3:00 AM UTC
    # - cron: '0 3 * * 1'
    # Sincronizza il calendario ogni Martedì alle 3:00 AM UTC
    # - cron: '0 3 * * 2'
  
  # Permette l'attivazione manuale dalla tab "Actions" di GitHub
  workflow_dispatch:

jobs:
  # Job per sincronizzare i risultati delle gare durante il weekend
  sync_race_results:
    name: Sync Race Results (Hourly on Race Weekend)
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 * * * 0,1,5,6'
    steps:
      - name: Check and Sync Race Results
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          API_URL: "https://fanta-motogp.vercel.app/api/sync/cron/sync-results"
        run: |
          curl --fail -X GET "$API_URL" -H "Authorization: Bearer $CRON_SECRET"

  # Job per sincronizzare la lista piloti una volta a settimana
  sync_riders:
    name: Sync Riders (Weekly)
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 3 * * 1'
    steps:
      - name: Sync Riders
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          API_URL: "https://fanta-motogp.vercel.app/api/sync/cron/sync-riders"
        run: |
          curl --fail -X GET "$API_URL" -H "Authorization: Bearer $CRON_SECRET"

  # Job per sincronizzare il calendario una volta a settimana
  sync_calendar:
    name: Sync Calendar (Weekly)
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 3 * * 2'
    steps:
      - name: Sync Calendar
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          API_URL: "https://fanta-motogp.vercel.app/api/sync/cron/sync-calendar"
        run: |
          curl --fail -X GET "$API_URL" -H "Authorization: Bearer $CRON_SECRET"

  # Job per l'esecuzione manuale di tutte le sincronizzazioni
  manual_sync_all:
    name: Manual Sync All
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Sync Riders
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl --fail -X GET "https://fanta-motogp.vercel.app/api/sync/cron/sync-riders" -H "Authorization: Bearer $CRON_SECRET"
      - name: Sync Calendar
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl --fail -X GET "https://fanta-motogp.vercel.app/api/sync/cron/sync-calendar" -H "Authorization: Bearer $CRON_SECRET"
      - name: Check and Sync Race Results
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl --fail -X GET "https://fanta-motogp.vercel.app/api/sync/cron/sync-results" -H "Authorization: Bearer $CRON_SECRET"